
google_site_verification : GtufKn6J_W8BuSqRiHOjSDzDaPHtFrCKN-LzZ7Kga6I

theme: jekyll-theme-minimal

title: [Pixel Scheduler]
description: [application in Apple app store]
logo: [https://user-images.githubusercontent.com/65215523/116958662-8d0e6e00-acc5-11eb-85b0-9e0bdfefe6f5.png]
